version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  deploychecks:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      #determine day of week, then hour of day, then based on that, load a different configruation file.
      - run:
          name: extract the commit message
          command: git log -1 --pretty=%B > changes.txt
      - run:
          name: Compares the commit message to a few different options.
          command: |
            cat changes.txt
            if grep -q alpha changes.txt;
            then echo alpha detected;
            elif grep -q beta changes.txt;
            then echo beta detected;
            else echo nothing found that matches
            fi
            
      - continuation/continue:
          configuration_path: .circleci/nextconfig.yml
workflows:
  deploychecks:
    jobs:
      - deploychecks
